name: Print Software Versions

on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # Перша робота для перевірки версій ПЗ на рівні обробки даних
  check-processing-software-versions:
    runs-on: windows-latest
    steps:
      - name: Виведення версії Node.js
        run: node --version

      - name: Виведення версії Java
        run: java -version

      - name: Виведення версії .NET Core
        run: dotnet --version

      - name: Виведення версії Angular CLI
        run: ng version || echo "Angular CLI не встановлений"

  # Друга робота для перевірки версії СКБД на рівні доступу до даних
  check-database-software-versions:
    runs-on: windows-latest
    steps:
      - name: Перевірка наявності MySQL
        shell: pwsh
        run: |
          $mysqlVersion = mysql --version
          if ($mysqlVersion) {
            Write-Host "MySQL вже встановлений."
          } else {
            Write-Host "MySQL не знайдено. Встановлюємо MySQL..."
            choco install mysql
            net start mysql
          }

      - name: Виведення версії MySQL
        run: mysql --version || echo "MySQL не встановлений"


